### ISSUE TITLE
App Crashes.

### ISSUE THREAD

**Issue by SamuelArnold** [sigint9/yaragui#2]
"An Unhandled Event, Win32 Exception occurred in YaraGui.exe [5440]"
more info using VS studio: 

"Unhandled exception at 0x69727666 (msvcr120.dll) in yaragui.exe: Fatal program exit requested."

When I do a scan of a directory such as C:/Windows/ 
with about 10 rules.
It will take about 999.MB ~ 1,014 MB of Ram and crash out.  Also It doesn't Save place or log.

**Comment by sigint9** [comment]
I feel that the per-file memory usage of the tool is reasonable and I also feel that it is reasonable that the memory usage grows with the number of files.

**Comment by SamuelArnold** [comment]
Thank you for answering back. So maybe just try to scan less directories at a time, is what your suggesting?

**Comment by sigint9** [comment]
I think that perhaps the GUI list would not even accommodate all of the results from the operating system directory that you tried to scan. Thanks for the report, but I cannot see a way to resolve this at the moment.
