### ISSUE TITLE
homepage is blank

### ISSUE THREAD

**Issue by wesinator** [sigint9/yaragui#4]
FYI , https://sigint9.github.io/yaragui/ is a blank page in Chrome and Firefox 

I came to it from https://github.com/x64dbg/yarasigs/#yara-signatures 

Thanks for this tool,

**Comment by sigint9** [comment]
Thanks, have tried to fix this by self-hosting the javascript web framework. It should work now.

**Comment by wesinator** [comment]
> Thanks, have tried to fix this by self-hosting the javascript web framework. It should work now.

thanks for this - FWIW, I think the issue was probably insecure cross-origin scripts loaded from http:// are not allowed on https pages. 

If you do `<script src="https://strapdownjs.com/v/0.2/strapdown.js">` , it'll probably work

Be well,
